version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: habitverse-app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      # Database configuration (MySQL)
      - DATABASE_URL=mysql+pymysql://habitverse:habitverse@mysql:3306/habitverse?charset=utf8mb4
      # Add other envs here, e.g. SECRET_KEY
    volumes:
      - ../app:/app/app:ro
      - ../alembic.ini:/app/alembic.ini:ro
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: habitverse-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=habitverse
      - MYSQL_USER=habitverse
      - MYSQL_PASSWORD=habitverse
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: habitverse-nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  db-data:
    driver: local